# Run with 'mkdocs serve'
# Build with 'mkdocs build'
# The documentation is available at https://lbae.epfl.ch/documentation/
# For updating the doc, please first build the doc locally, then copy the content of the local 'site' folder to the 'var/www/lbae-doc' folder.

site_name: LBAE technical documentation
repo_url: https://github.com/ColasDroin/lbae
site_url: https://lbae.epfl.ch
site_description: A web application to explore the mouse Lipid Brain Atlas.
site_author: Colas Droin

theme:
  name: "material"
  palette:
    scheme: slate
  features:
    - navigation.sections

plugins:
  - search
  - mkdocstrings

nav:
  - Welcome page: index.md
  - main: main.md
  - app: app.md
  - index: index_py.md
  - Modules:
      - atlas_labels: modules/atlas_labels.md
      - atlas: modules/atlas.md
      - figures: modules/figures.md
      - launch: modules/launch.md
      - maldi_data: modules/maldi_data.md
      - scRNAseq: modules/scRNAseq.md
      - storage: modules/storage.md
      - Tools:
          - modules/tools/atlas.md
          - modules/tools/image.md
          - modules/tools/lookup_tables.md
          - modules/tools/maldi_conversion.md
          - modules/tools/misc.md
          - modules/tools/spectra.md
          - modules/tools/volume.md
  - Pages:
      - home: pages/home.md
      - sidebar: pages/sidebar.md
      - load_slice: pages/load_slice.md
      - lipid_selection: pages/lipid_selection.md
      - region_analysis: pages/region_analysis.md
      - threeD_exploration: pages/threeD_exploration.md
      - scRNAseq: pages/scRNAseq.md
