site_name: LBAE technical documentation

theme:
  name: "material"
  palette:
    scheme: slate

plugins:
  - search
  - mkdocstrings

nav:
  - LBAE technical documentation home: index.md
  - Modules:
      - coucou test: test/index2.md
# Run with 'mkdocs serve'
# Build with 'mkdocs build'
