site_name: LBAE technical documentation

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings

nav:
  - LBAE technical documentation home: index.md
  - Modules:
      - coucou test: test/index2.md
